version: 2
jobs:
  build:
    docker:
      - image: node:9.11.1
    steps:
      - checkout
      - run:
          name: Lint CSS
          cache:
              untracked: true
              policy: pull
          command:
            |
            npm install
            ./node_modules/gulp/bin/gulp.js lint-css
      - run:
          name: Lint JS
          cache:
              untracked: true
              policy: pull
          command:
            |
            ./node_modules/gulp/bin/gulp.js lint-js
      - run:
          name: Deploying Staging
          environment:
            Environment: Staging
          only:
              - master
          command: |
            apt-get update && apt-get install -y sshpass
            sshpass -p$USER_PASS ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP "cd $STAGING_DIR && git pull -f"
      - run:
          name: Running & Waiting Test-Cases
          command: |
            git clone https://functionize@bitbucket.org/functionize/functionizecli.git /opt/functionizecli
            cd /opt/functionizecli
            npm install
            npm install -g
            wget -O - https://bitbucket.org/functionize/functionizecli/raw/master/ThirdParty_run.sh | bash
      - run:
          name: Deploying Production
          environment:
            Environment: Production
          only:
              - master
          command: |
            apt-get update && apt-get install -y sshpass
            sshpass -p$USER_PASS ssh -o StrictHostKeyChecking=no $USER@$SERVER_IP "cd $PRODUCTION_DIR && git pull -f"
